
import './global.css';
import Providers from './utils/provider';

export const metadata = {
  title: 'Welcome to next-frontend',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {


  return (
    <html lang="en">
      <Providers>
        <body>{children}</body>

      </Providers>
    </html>
  );
}
